#!/bin/sh

APP_PATH="$(dirname "$0")/../.."
LINK_FILE="$APP_PATH/Contents/Resources/Link.txt"

if test -e "$LINK_FILE"; then
  open -b "com.figma.Desktop" -- $(cat "$LINK_FILE")
else
  NEW_APP_NAME=$(osascript -e '
    tell app "Finder" to display dialog "Shortcut name:" default answer "New Figma Shortcut" buttons {"OK"} default button "OK"
    text returned of result
  ')

  NEW_APP_DIR="$(osascript -e '
    try
      tell app "Finder" to get POSIX path of ((target of window 1) as string)
    on error
      POSIX path of (path to desktop)
    end
  ')"
  NEW_APP_PATH="$NEW_APP_DIR/$NEW_APP_NAME.app"
  NEW_LINK_FILE="$NEW_APP_PATH/Contents/Resources/Link.txt"

  cp -a -R "$APP_PATH" "$NEW_APP_PATH"
  osascript -e '
    tell app "Finder" to display dialog "Figma URL:" default answer "'"$(pbpaste)"'" buttons {"OK"} default button "OK"
    text returned of result
  ' > "$NEW_LINK_FILE"
  open -R "$NEW_APP_PATH"
fi
